version: '3.8'

services:
  sveltefrontend:
    build:
      context: ./slidesV2
      dockerfile: Dockerfile
    container_name: sveltefrontend
    ports:
      - "5173:5173"
    restart: unless-stopped

  pythonbackend:
    build:
      context: ./python
      dockerfile: Dockerfile
    container_name: pythonbackend
    restart: unless-stopped
    entrypoint: ["sh", "-c", "while true; do python main.py; sleep 1800; done"]