# Use an official Python runtime as a parent image
FROM python:3.11-slim

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Run main.py when the container launches
CMD ["python", "main.py"]





# # Använd en lätt Python-bild
# FROM python:3.11-slim

# # Sätt arbetskatalog
# WORKDIR /app

# # Kopiera in requirements först (för caching)
# COPY python/requirements.txt /app/requirements.txt

# # Installera beroenden
# RUN pip install --no-cache-dir -r requirements.txt

# # Kopiera in all kod från python-mappen
# COPY python/ /app/

# # Ange standardkommando
# CMD ["python", "main.py"]

